//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "my_toggle_PinMux2.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"

#include <stdlib.h>

//*****************************************************************************
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);

    //
    // Enable pin PF1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF3 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);
}


int main(void)
{

	
		//initialize the GPIO ports	
		PortFunctionInit();
    
    //
    // Loop forever.
    //
    while(1)
    {
			
				// Generate a random integer
				int r = (rand() % 7);
	
        // Delay for a bit.
				SysCtlDelay(2000000);
			
			
			if (r == 0) {
				
				// Turn on the red LED.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
			
				// Turn off the red LED.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
			}
			
      else if(r == 1) {
				
				// Turn on the blue LED.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
			
				// Turn off the blue LED.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
			}
			
			else if(r == 2) {
				
				// Turn on the green LED.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
			
				// Turn off the green LED.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
			}
			
			
      else if(r == 3) {
				
				// Turn on the red/blue LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
				
				// Turn off the red/blue LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
			}
			
      else if(r == 4) {
				
				// Turn on the red/green LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
				
				// Turn off the red/green LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
			}
			
      else if(r == 5) {
				
				// Turn on the blue/green LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
				
				// Turn off the blue/green LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
			}
			
      else if(r == 6) {
				
				// Turn on the red/blue/green LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
			
        // Delay for a bit.
				SysCtlDelay(2000000);	
				
				// Turn off the red/blue/green LEDs.
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
			}

    }
}
